; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	;mbed-bxd/Adafruit_PWMServoDriver@0.0.0+sha.41a00db32ae7
    adafruit/Adafruit PWM Servo Driver Library@^3.0.1
;build_unflags = -std=gnu++11   ; 这行会移除默认的 C++11 编译参数，避免标准冲突
;build_flags = -std=gnu++17     ; 这行会强制使用更新的 C++17 标准来编译整个项目

build_src_filter = 
	+<main.cpp>
	-<test.cpp>